#!/bin/bash
nohup ~/app-root/data/perl-new/bin/perl ~/app-root/data/perl-new/bin/morbo --listen http://$OPENSHIFT_DIY_IP:$OPENSHIFT_DIY_PORT ~/app-root/runtime/repo/diy/script/taskio > /dev/null  2>&1 &
